clone_folder: C:\M
image: Visual Studio 2019

environment:
  DISABLE_QUALITY_CHECK: true
  PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Program Files\7-Zip
  BINTRAY_USER: jeroen
  BINTRAY_TARGET: rtools
  BINTRAY_PACKAGE: msys
  PACMAN_REPOSITORY: rtools
  BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
  MSYS_VERSION: msys64
  RTOOLS_ARCH: x86_64

install:
    - ps: Import-Module .\scripts.ps1
    - ps: UpdateMSYS2
#    - ps: InstallRtools

build_script:
#  - C:\%MSYS_VERSION%\usr\bin\bash.exe --login -c exit
#  - C:\%MSYS_VERSION%\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - xcopy /y pacman.conf C:\msys64\etc\pacman.conf
  - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm -Syyuu"
  - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm -Suu"
  - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

test: off

artifacts:
  - path: artifacts\*
    name: binaries
  - path: sourcepkg\*
    name: sources
